import { useState } from 'react';
import { Alert, Box, Button, FormControl, InputLabel, MenuItem, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography, useTheme } from '@mui/material';
import ScienceOutlinedIcon from '@mui/icons-material/ScienceOutlined';
import { Link as RouterLink } from 'react-router-dom';
import { errorMessage } from '../../api/governance';
import type { SimulationResult } from '../../api/policies';
import { ToneChip } from '../../components/Chips';
import { successTone } from '../../components/gov/GovChips';
import { Ellipsis } from '../../components/Primitives';
import { RANGES, rangeBounds } from '../../lib/range';
import { fmtNum } from '../../lib/format';

function SampleVerdict({ verdict }: { verdict: string }) { const t = useTheme().tokens; const v = verdict.toLowerCase(); const tone = v.includes('deny') ? t.severity.critical : v.includes('alert') ? t.severity.high : v.includes('approv') ? t.severity.high : v.includes('judge') ? t.severity.medium : successTone(t); return <ToneChip tone={tone} label={verdict} sx={{ height: 20, fontSize: 11 }} />; }
export function PolicySimulationResults({ result }: { result: SimulationResult }) { const t = useTheme().tokens; const tiles = [{ label: 'Evaluated', value: result.evaluated }, { label: 'Would allow', value: result.wouldAllow, color: t.success }, { label: 'Would deny', value: result.wouldDeny, color: t.severity.critical.fg }, { label: 'Would judge', value: result.wouldJudge, color: t.severity.medium.fg }, { label: 'Would approve', value: result.wouldApprove, color: t.severity.high.fg }, { label: 'Would alert', value: result.wouldAlert, color: t.severity.high.fg }]; return <Stack spacing={1.5} data-testid="policy-simulation-results"><Box sx={{ display: 'grid', gap: 1, gridTemplateColumns: 'repeat(auto-fit, minmax(110px, 1fr))' }}>{tiles.map(x => <Box key={x.label} sx={{ p: 1.25, border: '1px solid', borderColor: 'divider', borderRadius: 2 }} role="group" aria-label={`${x.label}: ${x.value}`}><Typography variant="caption" component="div">{x.label}</Typography><Typography sx={{ fontSize: 22, fontWeight: 600, color: x.color, fontVariantNumeric: 'tabular-nums' }}>{fmtNum(x.value)}</Typography></Box>)}</Box>{Object.keys(result.ruleHits ?? {}).length > 0 && <Box><Typography variant="subtitle2" sx={{ mb: 0.5 }}>Rule hits</Typography><Stack spacing={0.5}>{Object.entries(result.ruleHits).sort((a, b) => b[1] - a[1]).map(([id, n]) => <Stack key={id} direction="row" spacing={1} sx={{ alignItems: 'center' }}><Box sx={{ width: 90, fontVariantNumeric: 'tabular-nums' }}>{fmtNum(n)}</Box><Box sx={{ height: 8, borderRadius: 99, bgcolor: 'primary.main', width: Math.max(12, Math.min(220, n * 12)) }} /><Typography variant="caption" sx={{ fontFamily: 'var(--am-mono)' }}>{id}</Typography></Stack>)}</Stack></Box>}{result.samples.length > 0 ? <Box sx={{ overflowX: 'auto' }}><Table size="small" aria-label="Policy simulation samples"><TableHead><TableRow><TableCell>Verdict</TableCell><TableCell>Tool</TableCell><TableCell>Action</TableCell><TableCell>Rules</TableCell><TableCell /></TableRow></TableHead><TableBody>{result.samples.map(s => <TableRow key={`${s.eventId}`}><TableCell><SampleVerdict verdict={s.verdict} /></TableCell><TableCell sx={{ fontFamily: 'var(--am-mono)', fontSize: 12, whiteSpace: 'nowrap' }}>{s.tool ?? '?'}</TableCell><TableCell sx={{ maxWidth: 320 }}><Ellipsis text={s.summary} sx={{ display: 'block' }} /></TableCell><TableCell sx={{ fontFamily: 'var(--am-mono)', fontSize: 11.5 }}>{s.ruleIds.join(', ') || '?'}</TableCell><TableCell><Button size="small" component={RouterLink} to={`/conversations?c=${encodeURIComponent(s.sessionId)}`}>Session</Button></TableCell></TableRow>)}</TableBody></Table></Box> : <Typography variant="body2" color="text.secondary">No sample actions.</Typography>}</Stack>; }
export function PolicySimulatePanel({ yaml, disabled, simulate }: { yaml: string; disabled?: boolean; simulate: (body: { yaml?: string; from?: string; to?: string; limit?: number }) => Promise<SimulationResult> }) { const [range, setRange] = useState('7d'); const [result, setResult] = useState<SimulationResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const run = async () => { setBusy(true); setError(null); try { const { from, to } = rangeBounds(range); setResult(await simulate({ yaml, from, to, limit: 50 })); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }; return <Stack spacing={1.5}><Stack direction="row" spacing={1} sx={{ alignItems: 'center', flexWrap: 'wrap' }}><FormControl size="small" sx={{ minWidth: 140 }}><InputLabel id="policy-sim-range">History</InputLabel><Select labelId="policy-sim-range" label="History" value={range} onChange={e => setRange(e.target.value)}>{RANGES.map(r => <MenuItem key={r.key} value={r.key}>{r.label}</MenuItem>)}</Select></FormControl><Button variant="outlined" size="small" startIcon={<ScienceOutlinedIcon />} disabled={disabled || busy} onClick={() => void run()}>{busy ? 'Simulating?' : 'Simulate against history'}</Button></Stack>{disabled && <Typography variant="caption">Fix validation errors to simulate.</Typography>}{error && <Alert severity="error" role="alert">{error}</Alert>}{result && <PolicySimulationResults result={result} />}</Stack>; }
