import { useMemo, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Stack, Switch, Tab, Tabs, TextField, Typography } from '@mui/material';
import { DataGrid, type GridColDef, type GridRenderCellParams } from '@mui/x-data-grid';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import PolicyRoundedIcon from '@mui/icons-material/PolicyRounded';
import { Link as RouterLink, useNavigate, useSearchParams } from 'react-router-dom';
import { errorMessage } from '../../api/governance';
import { testClassifiers, useClassifiers, usePatchClassifier, usePolicies, usePresets, usePutClassifiersConfig, type Classifier, type ClassifierCategory, type ClassifierSensitivity, type CustomClassifierDef, type PolicyRecord, type PresetCatalog, type PresetEntry } from '../../api/policies';
import { useCan } from '../../auth/context';
import { CopyButton, EmptyState, SectionCard } from '../../components/Common';
import { QueryError } from '../../components/gov/GovCommon';
import { ToneChip } from '../../components/Chips';
import { RelativeTime } from '../../components/Primitives';
import { PolicyModeChip, PolicyStatusChip, SeverityToneChip } from './PolicyChips';

const TABS = ['policies', 'classifiers', 'presets'] as const;
const CATEGORIES: ClassifierCategory[] = ['Secrets', 'PII', 'Financial', 'Healthcare', 'Legal', 'Government', 'Infrastructure', 'Code', 'Prompt Injection', 'Education'];
const SENS: ClassifierSensitivity[] = ['Low', 'Medium', 'High'];
function SensitivityChip({ value }: { value: ClassifierSensitivity }) { const tone = value === 'High' ? 'critical' : value === 'Medium' ? 'medium' : 'low'; return <SeverityToneChip severity={tone} />; }
function counts(r: PolicyRecord) { const c: Record<string, number> = {}; for (const rule of r.policy.rules ?? []) c[rule.action] = (c[rule.action] ?? 0) + 1; return Object.entries(c).map(([k, v]) => `${k} ${v}`).join(' ? ') || 'No rules'; }
function PoliciesTab() { const [status, setStatus] = useState(''); const policies = usePolicies(status || undefined); const navigate = useNavigate(); const rows = policies.data ?? []; return <Stack spacing={2}><Stack direction="row" spacing={1} sx={{ alignItems: 'center' }}><FormControl size="small" sx={{ minWidth: 170 }}><InputLabel id="policy-status-filter">Status</InputLabel><Select labelId="policy-status-filter" label="Status" value={status} onChange={e => setStatus(e.target.value)}><MenuItem value="">All statuses</MenuItem>{['active','draft','proposed','archived'].map(s => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl><Box sx={{ flex: 1 }} /><Button variant="contained" size="small" startIcon={<AddRoundedIcon />} component={RouterLink} to="/policies/new">New policy</Button></Stack><Card>{policies.isError ? <QueryError error={policies.error} onRetry={() => void policies.refetch()} /> : !policies.isLoading && rows.length === 0 ? <EmptyState icon={<PolicyRoundedIcon />} title="No policies" body="Create global guardrails or attach policies to individual lanes." action={<Button size="small" component={RouterLink} to="/policies/new">New policy</Button>} /> : <Box sx={{ overflowX: 'auto' }}><Box component="table" sx={{ width: '100%', borderCollapse: 'collapse', '& th,& td': { p: 1.5, borderBottom: '1px solid', borderColor: 'divider', textAlign: 'left' } }} aria-label="Policies"><thead><tr><th>Policy</th><th>Scope</th><th>Mode</th><th>Severity</th><th>Rules</th><th>Status</th><th>Enabled</th><th>Updated</th></tr></thead><tbody>{rows.map(r => <tr key={`${r.policy.id}@${r.policy.version}`} tabIndex={0} onClick={() => navigate(`/policies/${encodeURIComponent(r.policy.id)}`)} onKeyDown={e => { if (e.key === 'Enter') navigate(`/policies/${encodeURIComponent(r.policy.id)}`); }} style={{ cursor: 'pointer' }}><td><Typography variant="body2" sx={{ fontWeight: 600 }}>{r.policy.name || r.policy.id}</Typography><Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'var(--am-mono)' }}>{r.policy.id}</Typography></td><td>{r.policy.global ? <ToneChip tone={themeTone()} label="Global" /> : 'attached'}</td><td><PolicyModeChip mode={r.policy.mode} /></td><td><SeverityToneChip severity={r.policy.severity} /></td><td>{counts(r)}</td><td><PolicyStatusChip status={r.status} /></td><td>{r.policy.enabled ? 'Yes' : 'No'}</td><td><RelativeTime iso={r.updatedAt} /></td></tr>)}</tbody></Box></Box>}</Card></Stack>; }
function themeTone() { return { fg: 'var(--mui-palette-success-main)', bg: 'rgba(34,197,94,0.12)', border: 'rgba(34,197,94,0.32)' }; }
function ClassifierSwitch({ cls, field, disabled }: { cls: Classifier; field: 'isActive' | 'enforceable'; disabled: boolean }) { const patch = usePatchClassifier(); return <Switch checked={!!cls[field]} disabled={disabled || patch.isPending} slotProps={{ input: { 'aria-label': `${field === 'isActive' ? 'Active' : 'Enforceable'} ${cls.code}` } }} onChange={e => patch.mutate({ code: cls.code, patch: { [field]: e.target.checked } })} />; }
function TestPanel({ codes }: { codes?: string[] }) { const [text, setText] = useState(''); const [result, setResult] = useState<{ detections: { key: string; label: string; maskedSample: string }[]; errors: string[] } | null>(null); const [err, setErr] = useState<string | null>(null); const run = async () => { setErr(null); try { setResult(await testClassifiers({ text, codes })); } catch (e) { setErr(errorMessage(e)); } }; return <Stack spacing={1}><TextField label="Test text" multiline minRows={3} value={text} onChange={e => setText(e.target.value)} /><Button size="small" variant="outlined" disabled={!text.trim()} onClick={() => void run()} sx={{ alignSelf: 'flex-start' }}>Run classifier test</Button>{err && <Alert severity="error">{err}</Alert>}{result && <Stack spacing={0.5}>{result.errors.map(e => <Alert key={e} severity="error">{e}</Alert>)}{result.detections.map(d => <Typography key={`${d.key}-${d.maskedSample}`} variant="body2"><Box component="span" sx={{ fontFamily: 'var(--am-mono)' }}>{d.key}</Box> ? {d.label}: {d.maskedSample}</Typography>)}</Stack>}</Stack>; }
function AddClassifierDialog({ open, onClose }: { open: boolean; onClose: () => void }) { const q = useClassifiers(); const put = usePutClassifiersConfig(); const [draft, setDraft] = useState<CustomClassifierDef>({ code: '', label: '', category: 'Secrets', sensitivity: 'High', pattern: '', isActive: true, enforceable: true }); const [error, setError] = useState<string | null>(null); const save = async () => { if (!q.data) return; setError(null); try { await put.mutateAsync({ ...q.data.config, custom: [...(q.data.config.custom ?? []), draft] }); onClose(); } catch (e) { setError(errorMessage(e)); } }; return <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth><DialogTitle>Add custom classifier</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Code" value={draft.code} onChange={e => setDraft({ ...draft, code: e.target.value })} helperText="lowercase_snake" /><TextField label="Label" value={draft.label} onChange={e => setDraft({ ...draft, label: e.target.value })} /><Stack direction="row" spacing={2}><FormControl size="small" sx={{ minWidth: 180 }}><InputLabel id="new-cls-cat">Category</InputLabel><Select labelId="new-cls-cat" label="Category" value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value as ClassifierCategory })}>{CATEGORIES.map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth: 160 }}><InputLabel id="new-cls-sens">Sensitivity</InputLabel><Select labelId="new-cls-sens" label="Sensitivity" value={draft.sensitivity} onChange={e => setDraft({ ...draft, sensitivity: e.target.value as ClassifierSensitivity })}>{SENS.map(s => <MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Stack><TextField label="Pattern" value={draft.pattern} onChange={e => setDraft({ ...draft, pattern: e.target.value })} /><TextField label="Context pattern" value={draft.contextPattern ?? ''} onChange={e => setDraft({ ...draft, contextPattern: e.target.value || undefined })} /><TextField label="Flags" value={draft.flags ?? ''} onChange={e => setDraft({ ...draft, flags: e.target.value || undefined })} /><TestPanel codes={undefined} />{error && <Alert severity="error">{error}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!draft.code || !draft.label || !draft.pattern || put.isPending} onClick={() => void save()}>Save</Button></DialogActions></Dialog>; }
function ClassifiersTab() { const q = useClassifiers(); const admin = useCan('PolicyAdmin'); const [category, setCategory] = useState(''); const [sens, setSens] = useState(''); const [search, setSearch] = useState(''); const [dialog, setDialog] = useState(false); const rows = useMemo(() => (q.data?.items ?? []).filter(c => (!category || c.category === category) && (!sens || c.sensitivity === sens) && (!search || `${c.label} ${c.code} ${c.description}`.toLowerCase().includes(search.toLowerCase()))), [q.data, category, sens, search]); const cols: GridColDef<Classifier>[] = [{ field: 'label', headerName: 'Label', flex: 1, minWidth: 180, renderCell: p => <Stack spacing={0}><Typography variant="body2">{p.row.label}</Typography>{p.row.aliasOf && <ToneChip tone={themeTone()} label={`alias of ${p.row.aliasOf}`} sx={{ height: 18, fontSize: 10 }} />}</Stack> }, { field: 'code', headerName: 'Code', minWidth: 160 }, { field: 'category', headerName: 'Category', minWidth: 150 }, { field: 'sensitivity', headerName: 'Sensitivity', minWidth: 130, renderCell: (p: GridRenderCellParams<Classifier, ClassifierSensitivity>) => <SensitivityChip value={p.value ?? 'Low'} /> }, { field: 'isActive', headerName: 'Active', minWidth: 100, renderCell: p => <ClassifierSwitch cls={p.row} field="isActive" disabled={!admin} /> }, { field: 'enforceable', headerName: 'Enforceable', minWidth: 130, renderCell: p => <ClassifierSwitch cls={p.row} field="enforceable" disabled={!admin} /> }, { field: 'source', headerName: 'Source', minWidth: 100 }]; return <Stack spacing={2}><Stack direction="row" spacing={1} sx={{ alignItems: 'center', flexWrap: 'wrap' }}><TextField size="small" label="Search" value={search} onChange={e => setSearch(e.target.value)} /><Autocomplete size="small" options={CATEGORIES} value={category || null} onChange={(_, v) => setCategory(v ?? '')} renderInput={params => <TextField {...params} label="Category" />} sx={{ minWidth: 190 }} /><Autocomplete size="small" options={SENS} value={(sens || null) as ClassifierSensitivity | null} onChange={(_, v) => setSens(v ?? '')} renderInput={params => <TextField {...params} label="Sensitivity" />} sx={{ minWidth: 160 }} /><Box sx={{ flex: 1 }} /><Button size="small" variant="outlined" startIcon={<AddRoundedIcon />} disabled={!admin} onClick={() => setDialog(true)}>Add custom classifier</Button></Stack>{q.isError ? <QueryError error={q.error} onRetry={() => void q.refetch()} /> : <DataGrid autoHeight rows={rows} columns={cols} getRowId={r => r.code} disableRowSelectionOnClick pageSizeOptions={[10, 25, 50]} initialState={{ pagination: { paginationModel: { pageSize: 10 } } }} />}<SectionCard title="Test text" subtitle="Run all active classifiers against arbitrary text."><TestPanel codes={(q.data?.items ?? []).filter(c => c.isActive).map(c => c.code)} /></SectionCard><AddClassifierDialog open={dialog} onClose={() => setDialog(false)} /></Stack>; }
function PresetGroup({ title, items }: { title: string; items: PresetEntry[] }) { const byGroup = items.reduce<Record<string, PresetEntry[]>>((acc, item) => { (acc[item.group] ??= []).push(item); return acc; }, {}); return <SectionCard title={title}>{Object.entries(byGroup).map(([group, entries]) => <Box key={group} sx={{ mb: 2 }}><Typography variant="subtitle2" sx={{ mb: 1 }}>{group}</Typography><Stack spacing={1}>{entries.map(e => <Card key={e.id} variant="outlined" sx={{ p: 1.5 }}><Stack direction="row" spacing={1} sx={{ alignItems: 'flex-start' }}><Box sx={{ flex: 1 }}><Typography variant="body2" sx={{ fontWeight: 600 }}>{e.label}</Typography><Typography variant="caption" sx={{ fontFamily: 'var(--am-mono)' }}>{e.id}</Typography><Typography variant="body2" color="text.secondary">{e.description}</Typography><Stack direction="row" spacing={0.5} sx={{ flexWrap: 'wrap', mt: 0.75 }}>{(Array.isArray(e.pattern) ? e.pattern : [e.pattern]).map(pattern => <ToneChip key={pattern} tone={themeTone()} label={pattern} sx={{ fontFamily: 'var(--am-mono)' }} />)}{e.subsetOf && <ToneChip tone={themeTone()} label={`part of ${e.subsetOf}`} />}</Stack></Box><CopyButton text={e.id} label={`Copy ${e.id}`} /></Stack></Card>)}</Stack></Box>)}</SectionCard>; }
function PresetsTab() { const q = usePresets(); if (q.isError) return <QueryError error={q.error} onRetry={() => void q.refetch()} />; const data: PresetCatalog = q.data ?? { filesystem: [], network: [], credential: [], capability: [], mcpCategory: [] }; return <Stack spacing={2}><PresetGroup title="Filesystem" items={data.filesystem} /><PresetGroup title="Network" items={data.network} /><PresetGroup title="Credentials" items={data.credential} /><PresetGroup title="Capabilities" items={data.capability} /><PresetGroup title="MCP categories" items={data.mcpCategory} /></Stack>; }
export function PoliciesPage() { const [params, setParams] = useSearchParams(); const current = (params.get('tab') || 'policies') as typeof TABS[number]; const tab = TABS.includes(current) ? current : 'policies'; const setTab = (v: string) => setParams(prev => { const n = new URLSearchParams(prev); n.set('tab', v); return n; }); return <Stack spacing={2.5}><Stack spacing={0.5}><Typography variant="h5" component="h2">Policies</Typography><Typography variant="body2" color="text.secondary">Create reusable governance policies, maintain sensitive-data classifiers, and browse preset condition catalogues.</Typography></Stack><Tabs value={tab} onChange={(_, v) => setTab(v)} aria-label="Policy sections"><Tab value="policies" label="Policies" /><Tab value="classifiers" label="Data classifiers" /><Tab value="presets" label="Presets" /></Tabs>{tab === 'policies' ? <PoliciesTab /> : tab === 'classifiers' ? <ClassifiersTab /> : <PresetsTab />}</Stack>; }

