import { abaChecksum, cusipCheck, deaChecksum, einPrefixValid, ibanMod97, isinCheck, luhn, ssnValid, tfnChecksum, verhoeff, vinCheckDigit } from './validators';

export type ClassifierCategory = 'Secrets' | 'PII' | 'Financial' | 'Healthcare' | 'Legal' | 'Government' | 'Infrastructure' | 'Code' | 'Prompt Injection' | 'Education';
export type ClassifierSensitivity = 'Low' | 'Medium' | 'High';
export type ClassifierSource = 'builtin' | 'custom';

export interface ClassifierEntry {
  code: string;
  label: string;
  description: string;
  category: ClassifierCategory;
  sensitivity: ClassifierSensitivity;
  contextRequired: boolean;
  isActive: boolean;
  enforceable: boolean;
  source: ClassifierSource;
  re: RegExp;
  group?: number;
  context?: RegExp;
  aliasOf?: string;
  validate?: (value: string, match?: RegExpExecArray, text?: string) => boolean;
}

export const EMAIL_IGNORE = /(^git@|noreply|no-reply|@example\.(com|org|net)$|@users\.noreply\.github\.com$|@localhost$|@anthropic\.com$|@copilot\.)/i;

export function looksLikePlaceholder(v: string): boolean {
  if (v.includes('****') || /\[REDACTED\]/.test(v)) return true;
  if (/^[$<{%[(]/.test(v)) return true;
  if (/^(x+|\*+|\.+|-+|_+|0+|changeme|placeholder|redacted|your[-_a-z]*|example|dummy|test|none|null|undefined|true|false)$/i.test(v)) return true;
  if (/^(.)\1+$/.test(v)) return true;
  if (/(process\.env|os\.environ|getenv|\$env:)/i.test(v)) return true;
  return false;
}

function valueLikeSecret(v: string): boolean {
  return !looksLikePlaceholder(v) && /[A-Za-z]/.test(v) && /\d/.test(v);
}
function digits(v: string): string { return v.replace(/\D/g, ''); }
function validIPv4(v: string): boolean { return v.split('.').every(p => /^\d{1,3}$/.test(p) && Number(p) <= 255); }
function isPrivateIPv4(v: string): boolean {
  const p = v.split('.').map(Number);
  return p[0] === 10 || (p[0] === 172 && p[1] >= 16 && p[1] <= 31) || (p[0] === 192 && p[1] === 168) || p[0] === 127 || (p[0] === 169 && p[1] === 254);
}
function validCredit(value: string, prefix: RegExp, lengths: number[]): boolean {
  const d = digits(value);
  return lengths.includes(d.length) && prefix.test(d) && luhn(d);
}
function aadhaarValid(value: string): boolean { const d = digits(value); return /^[2-9]\d{11}$/.test(d) && verhoeff(d); }
function npiValid(value: string): boolean { const d = digits(value); return /^\d{10}$/.test(d) && luhn('80840' + d); }
function envFileValid(value: string): boolean {
  const lines = value.split(/\r?\n/).filter(Boolean);
  return lines.length >= 2 && lines.some(l => /(?:SECRET|TOKEN|PASSWORD|PASSWD|PWD|API_?KEY|ACCESS_KEY|PRIVATE_KEY|CLIENT_SECRET|CONN(?:ECTION)?_?STRING)/i.test(l))
    && lines.some(l => valueLikeSecret(l.split(/[:=]/).slice(1).join('=').trim().replace(/^['"]|['"]$/g, '')));
}

const passportContext = /\bpassport\b/i;
const bankContext = /\b(bank|account|acct|routing|ach|aba|wire|iban|swift|bic)\b/i;

export const BUILTIN_CLASSIFIERS: ClassifierEntry[] = [
  { code: 'private_key', label: 'Private Key', description: 'PEM private key block marker', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP |ENCRYPTED )?PRIVATE KEY-----/g },
  { code: 'github_token', label: 'Secret Key (GitHub)', description: 'GitHub personal, OAuth, user, server, refresh, and fine-grained tokens', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:gh[pousr]_[A-Za-z0-9]{36,}|github_pat_[A-Za-z0-9_]{60,})\b/g },
  { code: 'aws_key', label: 'Secret Key (AWS)', description: 'AWS access key identifiers', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/g },
  { code: 'ai_key', label: 'Secret Key (AI provider)', description: 'OpenAI, Anthropic, and similar sk-prefixed provider keys', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\bsk-(?:ant-|proj-)?[A-Za-z0-9_-]{32,}\b/g },
  { code: 'slack_token', label: 'Secret Key (Slack)', description: 'Slack tokens (xoxb-, xoxa-, xoxp-, xoxr-, xoxs-)', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g },
  { code: 'google_key', label: 'Secret Key (Google)', description: 'Google API keys', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\bAIza[0-9A-Za-z_-]{35}\b/g },
  { code: 'azure_conn', label: 'Azure Connection String', description: 'Azure Storage, Service Bus, Cosmos, and Application Insights connection strings', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /(?:DefaultEndpointsProtocol=https?;AccountName=[^;"\s]+;AccountKey=[^;"\s]{20,}|Endpoint=sb:\/\/[^;"\s]+;SharedAccessKeyName=[^;"\s]+;SharedAccessKey=[^;"\s]{20,}|AccountEndpoint=https:\/\/[^;"\s]+;AccountKey=[^;"\s]{20,}|InstrumentationKey=[0-9a-f-]{36};)/gi },
  { code: 'jwt', label: 'JSON Web Token', description: 'JWT bearer tokens', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g },
  { code: 'env_secret', label: 'Secret in env var', description: 'Secret-like environment variable assignment', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', group: 2, re: /\b((?=[A-Z0-9_]*(?:SECRET|TOKEN|PASSWORD|PASSWD|PWD|API_?KEY|ACCESS_KEY|PRIVATE_KEY|CLIENT_SECRET|CONN(?:ECTION)?_?STRING))[A-Z][A-Z0-9_]*)\s*[=:]\s*\\?["']?([^\s"'\\,;]{8,})/g, validate: valueLikeSecret },
  { code: 'password_url', label: 'Password in URL', description: 'Credentials embedded in URLs', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', group: 1, re: /\b[a-z][a-z0-9+.-]*:\/\/[^\s:@/"']+:([^\s@/"']{3,})@[a-z0-9.-]+/gi, validate: v => !looksLikePlaceholder(v) },
  { code: 'aws_secret_key', label: 'AWS Secret Access Key', description: 'AWS secret access keys (40-character base64, requires context)', category: 'Secrets', sensitivity: 'High', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b[A-Za-z0-9/+=]{40}\b/g, context: /\baws(?:_|\s|-)?(?:secret|access)|secret(?:_|\s|-)?access(?:_|\s|-)?key\b/i, validate: v => /[A-Za-z]/.test(v) && /\d/.test(v) && !looksLikePlaceholder(v) },
  { code: 'generic_api_key', label: 'Generic API Key', description: 'API keys assigned via key=value or key:value syntax', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', group: 2, re: /\b([A-Za-z0-9_.-]*(?:api[_-]?key|secret[_-]?key|access[_-]?token|auth[_-]?token)[A-Za-z0-9_.-]*)\s*[:=]\s*["']?([A-Za-z0-9][A-Za-z0-9_\-./=+]{15,})["']?/gi, validate: valueLikeSecret },
  { code: 'slack_bot_token', label: 'Slack Token', description: 'Slack bot, user, and app tokens (xoxb-, xoxp-, xoxs-)', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', aliasOf: 'slack_token', re: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g },
  { code: 'stripe_secret', label: 'Stripe API Key', description: 'Stripe live and restricted keys', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:sk|rk|pk)_live_[A-Za-z0-9]{16,}\b/g },
  { code: 'stripe_test_key', label: 'Stripe Test API Key', description: 'Stripe test environment keys (lower sensitivity)', category: 'Secrets', sensitivity: 'Low', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:sk|rk|pk)_test_[A-Za-z0-9]{16,}\b/g },
  { code: 'nuget_api_key', label: 'NuGet API Key', description: 'NuGet package registry API keys', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\boy2[a-z0-9]{43}\b/gi },
  { code: 'twilio_sid', label: 'Twilio Credentials', description: 'Twilio Account SID and API keys with context', category: 'Secrets', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:AC|SK)[0-9a-f]{32}\b/g, context: /\btwilio|account sid|auth token\b/i },
  { code: 'shopify_token', label: 'Shopify Access Token', description: 'Shopify admin and storefront access tokens', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\bshp(?:at|ca|pa|ss)_[A-Za-z0-9]{16,}\b/g },
  { code: 'discord_token', label: 'Discord Bot Token', description: 'Discord bot authentication tokens', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b[A-Za-z\d_-]{24}\.[A-Za-z\d_-]{6}\.[A-Za-z\d_-]{27,}\b/g },
  { code: 'heroku_api_key', label: 'Heroku API Key', description: 'Heroku API keys in UUID format with context', category: 'Secrets', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/gi, context: /\bheroku\b/i },
  { code: 'mailgun_api_key', label: 'Mailgun API Key', description: 'Mailgun API keys', category: 'Secrets', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\bkey-[0-9a-f]{32}\b/gi },
  { code: 'datadog_api_key', label: 'Datadog API Key', description: 'Datadog API and application keys', category: 'Secrets', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b[0-9a-f]{32}\b/gi, context: /\b(?:dd|datadog)(?:_|\s|-)?(?:api|app|application)?(?:_|\s|-)?key\b/i },
  { code: 'private_key_pkcs8', label: 'Private Key (PKCS#8)', description: 'PKCS#8 encoded private key content', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /-----BEGIN PRIVATE KEY-----/g },
  { code: 'ssh_private_key_content', label: 'SSH Private Key Content', description: 'SSH private key file content including OpenSSH format', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /-----BEGIN OPENSSH PRIVATE KEY-----/g },
  { code: 'certificate_pem', label: 'X.509 Certificate', description: 'PEM-encoded X.509 certificate (may indicate key proximity)', category: 'Secrets', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /-----BEGIN CERTIFICATE-----/g },
  { code: 'oauth_client_secret', label: 'OAuth Client Secret', description: 'OAuth client secrets in configuration or code context', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', group: 1, re: /\bclient_secret\s*[:=]\s*["']?([A-Za-z0-9_~.\-]{12,})["']?/gi, validate: v => !looksLikePlaceholder(v) },
  { code: 'connection_string_jdbc', label: 'JDBC Connection String', description: 'Java Database Connectivity connection strings with credentials', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\bjdbc:[^\s;"']+(?:;[^\s;"']+)*;password=[^;"'\s]+/gi },
  { code: 'connection_string_odbc', label: 'ODBC Connection String', description: 'ODBC connection strings potentially containing credentials', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:Driver=\{?[^;\n]+}?;[^\n]{0,300}?Pwd=[^;\s]+|Pwd=[^;\s]+;[^\n]{0,300}?Driver=\{?[^;\n]+}?)/gi },
  { code: 'env_file_content', label: '.env File Content', description: 'Environment variable assignments commonly found in .env files', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /(?:^|\n)(?:[A-Z][A-Z0-9_]{2,}\s*=\s*[^\n]{3,}\n){1,}[A-Z][A-Z0-9_]{2,}\s*=\s*[^\n]{3,}/gm, validate: envFileValid },
  { code: 'azure_ad_client_secret', label: 'Azure AD Client Secret', description: 'Azure Active Directory / Entra ID application client secrets', category: 'Secrets', sensitivity: 'High', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b[A-Za-z0-9_~.-]{3}8Q~[A-Za-z0-9_~.-]{31,34}\b/g, context: /\b(?:client_secret|azure|entra|tenant|app registration)\b/i },
  { code: 'gcp_service_account_key', label: 'GCP Service Account Key', description: 'Google Cloud Platform service account JSON key file content', category: 'Secrets', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /"type"\s*:\s*"service_account"[\s\S]{0,2000}?"private_key"\s*:\s*"-----BEGIN PRIVATE KEY-----/g },
  { code: 'email', label: 'Email Address', description: 'Standard email address format', category: 'PII', sensitivity: 'Low', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g, validate: v => !EMAIL_IGNORE.test(v) && !/\.(png|jpe?g|gif|svg|webp|js|ts|css)$/i.test(v) },
  { code: 'us_ssn', label: 'US Social Security Number', description: 'US SSN in XXX-XX-XXXX format', category: 'PII', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b\d{3}-\d{2}-\d{4}\b/g, validate: ssnValid },
  { code: 'ssn_no_dashes', label: 'US SSN (no dashes)', description: 'US SSN as 9 consecutive digits requiring context', category: 'PII', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b\d{9}\b/g, context: /\b(?:ssn|social security)\b/i, validate: ssnValid },
  { code: 'phone_international_e164', label: 'International Phone (E.164)', description: 'International phone numbers in E.164 format (+country code)', category: 'PII', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\+[1-9]\d{7,14}\b/g },
  { code: 'uk_nino', label: 'UK National Insurance Number', description: 'UK NINO in standard format', category: 'PII', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?!BG|GB|KN|NK|NT|TN|ZZ)[A-CEGHJ-PR-TW-Z]{2}\s?\d{2}\s?\d{2}\s?\d{2}\s?[A-D]\b/gi },
  { code: 'canadian_sin', label: 'Canadian SIN', description: 'Canadian Social Insurance Number in XXX-XXX-XXX format with Luhn validation', category: 'PII', sensitivity: 'High', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b\d{3}[- ]?\d{3}[- ]?\d{3}\b/g, context: /\b(?:sin|social insurance)\b/i, validate: luhn },
  { code: 'indian_aadhaar', label: 'Indian Aadhaar Number', description: 'Indian Aadhaar unique identity number (12 digits)', category: 'PII', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b[2-9]\d{3}\s?\d{4}\s?\d{4}\b/g, validate: aadhaarValid },
  { code: 'australian_tfn', label: 'Australian Tax File Number', description: 'Australian TFN (8-9 digits with weighted checksum)', category: 'PII', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{3}\s?\d{3}\s?\d{3}\b/g, context: /\b(?:tfn|tax file number)\b/i, validate: tfnChecksum },
  { code: 'date_of_birth', label: 'Date of Birth', description: 'Date of birth in common formats requiring PII or medical context', category: 'PII', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', group: 1, re: /\b(?:DOB|date of birth|birth date)\s*[:=-]?\s*(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\d{4}-\d{2}-\d{2})\b/gi },
  { code: 'us_physical_address', label: 'US Physical Address', description: 'US street addresses with number, street name, and type', category: 'PII', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{1,6}\s+[A-Za-z0-9.'-]+(?:\s+[A-Za-z0-9.'-]+){0,4}\s+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Lane|Ln|Drive|Dr|Court|Ct|Way)\b/gi },
  { code: 'vin', label: 'Vehicle Identification Number', description: '17-character VIN excluding I, O, Q (requires context)', category: 'PII', sensitivity: 'Low', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-HJ-NPR-Z0-9]{17}\b/g, context: /\b(?:vin|vehicle identification|vehicle)\b/i, validate: vinCheckDigit },
  { code: 'us_passport_number', label: 'US Passport Number', description: 'US passport numbers (9 digits or 1 letter + 8 digits)', category: 'PII', sensitivity: 'High', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:[A-Z]\d{8}|\d{9})\b/g, context: passportContext },
  { code: 'passport_uk', label: 'UK Passport Number', description: 'United Kingdom passport number (9 digits)', category: 'PII', sensitivity: 'High', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{9}\b/g, context: /\b(?:uk|british|united kingdom) passport\b/i },
  { code: 'passport_eu', label: 'EU Passport Number', description: 'European Union passport numbers (alphanumeric, 7-9 characters)', category: 'PII', sensitivity: 'High', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z0-9]{7,9}\b/g, context: /\b(?:eu|european) passport\b/i },
  { code: 'passport_canada', label: 'Canadian Passport Number', description: 'Canadian passport number (2 letters + 6 digits)', category: 'PII', sensitivity: 'High', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z]{2}\d{6}\b/g, context: /\bcanad(?:a|ian) passport\b/i },
  { code: 'passport_australia', label: 'Australian Passport Number', description: 'Australian passport number (1-2 letters + 7 digits)', category: 'PII', sensitivity: 'High', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z]{1,2}\d{7}\b/g, context: /\baustralian passport\b/i },
  { code: 'german_personalausweis', label: 'German National ID', description: 'German ID card number (10 alphanumeric characters)', category: 'PII', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z0-9]{10}\b/g, context: /\b(?:personalausweis|german (?:national )?id)\b/i },
  { code: 'french_national_id', label: 'French National ID (INSEE)', description: 'French social security number (NIR) — 13 digits + 2-digit key', category: 'PII', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[12]\s?\d{2}\s?(?:0[1-9]|1[0-2])\s?\d{2}\s?\d{3}\s?\d{3}\s?\d{2}\b/g, context: /\b(?:insee|nir|french national|french social)\b/i },
  { code: 'drivers_license_ca', label: 'California Driver\'s License', description: 'California DL number: 1 letter + 7 digits', category: 'PII', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z]\d{7}\b/g, context: /\b(?:california|ca)\s*(?:driver'?s license|dl)\b/i },

  { code: 'credit_card_visa', label: 'Visa Card Number', description: 'Visa credit card numbers with Luhn validation', category: 'Financial', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b4(?:\d[ -]?){12}(?:(?:\d[ -]?){3})?\b/g, validate: v => validCredit(v, /^4/, [13, 16]) },
  { code: 'credit_card_mastercard', label: 'Mastercard Number', description: 'Mastercard numbers with Luhn validation', category: 'Financial', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:5[1-5]\d{2}|2[2-7]\d{2})(?:[ -]?\d){12}\b/g, validate: v => validCredit(v, /^(5[1-5]|2[2-7])/, [16]) },
  { code: 'credit_card_amex', label: 'American Express Number', description: 'Amex card numbers with Luhn validation', category: 'Financial', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b3[47]\d{2}(?:[ -]?\d){11}\b/g, validate: v => validCredit(v, /^3[47]/, [15]) },
  { code: 'credit_card_discover', label: 'Discover Card Number', description: 'Discover card numbers with Luhn validation', category: 'Financial', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b6(?:011|5\d{2})(?:[ -]?\d){12}\b/g, validate: v => validCredit(v, /^(6011|65)/, [16]) },
  { code: 'credit_card_diners', label: 'Diners Club Number', description: 'Diners Club card numbers with Luhn validation', category: 'Financial', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b3(?:0[0-5]|[68]\d)\d(?:[ -]?\d){10}\b/g, validate: v => validCredit(v, /^3(0[0-5]|[68])/, [14]) },
  { code: 'credit_card_jcb', label: 'JCB Card Number', description: 'JCB card numbers with Luhn validation', category: 'Financial', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b(?:2131|1800|35\d{2})(?:[ -]?\d){11,12}\b/g, validate: v => validCredit(v, /^(2131|1800|35)/, [15, 16]) },
  { code: 'iban', label: 'IBAN', description: 'International Bank Account Number (requires context)', category: 'Financial', sensitivity: 'High', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b/g, context: bankContext, validate: ibanMod97 },
  { code: 'swift_code', label: 'SWIFT/BIC Code', description: 'SWIFT/BIC codes used for international wire transfers (requires context)', category: 'Financial', sensitivity: 'Low', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b/g, context: /\b(?:swift|bic|wire transfer)\b/i },
  { code: 'ach_routing_number', label: 'ACH Routing Number', description: 'US ACH/ABA routing transit numbers (9 digits with checksum, requires context)', category: 'Financial', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b\d{9}\b/g, context: /\b(?:routing|aba|ach)\b/i, validate: abaChecksum },
  { code: 'us_bank_account', label: 'US Bank Account Number', description: 'US bank account numbers (6-17 digits, requires banking context)', category: 'Financial', sensitivity: 'High', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b\d{6,17}\b/g, context: /\b(?:bank account|account number|acct)\b/i },
  { code: 'tax_id_ein', label: 'Tax ID / EIN', description: 'US Employer Identification Number in XX-XXXXXXX format (requires context)', category: 'Financial', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /\b\d{2}-\d{7}\b/g, context: /\b(?:ein|employer identification|tax id)\b/i, validate: einPrefixValid },
  { code: 'cusip', label: 'CUSIP', description: 'Securities identification number (9 chars with check digit, requires context)', category: 'Financial', sensitivity: 'Low', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[0-9A-Z*@#]{9}\b/g, context: /\bcusip\b/i, validate: cusipCheck },
  { code: 'isin', label: 'ISIN', description: 'International Securities Identification Number (requires context)', category: 'Financial', sensitivity: 'Low', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z]{2}[A-Z0-9]{9}\d\b/g, context: /\bisin\b/i, validate: isinCheck },
  { code: 'crypto_bitcoin_address', label: 'Bitcoin Wallet Address', description: 'Bitcoin addresses in legacy, SegWit, and Bech32 formats (requires context)', category: 'Financial', sensitivity: 'Medium', contextRequired: true, isActive: true, enforceable: true, source: 'builtin', re: /(?:\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b|\bbc1[ac-hj-np-z02-9]{11,71}\b)/gi, context: /\b(?:bitcoin|btc|wallet)\b/i },
  { code: 'crypto_ethereum_address', label: 'Ethereum Wallet Address', description: 'Ethereum addresses (0x prefix + 40 hex characters)', category: 'Financial', sensitivity: 'Medium', contextRequired: false, isActive: true, enforceable: true, source: 'builtin', re: /\b0x[0-9a-fA-F]{40}\b/g },
  { code: 'npi_number', label: 'NPI (National Provider ID)', description: '10-digit NPI used to identify healthcare providers with Luhn check', category: 'Healthcare', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{10}\b/g, context: /\b(?:npi|provider)\b/i, validate: npiValid },
  { code: 'dea_number', label: 'DEA Number', description: 'Drug Enforcement Administration registration number (requires context)', category: 'Healthcare', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-Z]{2}\d{7}\b/g, context: /\bdea\b/i, validate: deaChecksum },
  { code: 'ndc_code', label: 'National Drug Code (NDC)', description: 'NDC codes in 4-4-2, 5-3-2, or 5-4-1 format (requires context)', category: 'Healthcare', sensitivity: 'Low', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{4,5}-\d{3,4}-\d{1,2}\b/g, context: /\b(?:ndc|drug)\b/i },
  { code: 'icd10_code', label: 'ICD-10 Diagnosis Code', description: 'ICD-10-CM diagnosis codes (requires context)', category: 'Healthcare', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[A-TV-Z][0-9][0-9A-Z](?:\.[0-9A-Z]{1,4})?\b/g, context: /\b(?:icd-?10|diagnosis|dx)\b/i },
  { code: 'medical_record_number', label: 'Medical Record Number (MRN)', description: 'Hospital/clinic medical record numbers in common formats', category: 'Healthcare', sensitivity: 'High', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', group: 1, re: /\b(?:MRN|medical record)\s*[:#-]?\s*([A-Z0-9-]{6,12})\b/gi },
  { code: 'health_plan_beneficiary', label: 'Health Plan Beneficiary Number', description: 'Medicare Beneficiary Identifier (MBI) format (requires context)', category: 'Healthcare', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b[1-9][AC-HJ-NP-RT-Y][A-HJ-NP-Z0-9]\d[AC-HJ-NP-RT-Y][A-HJ-NP-Z0-9]\d[AC-HJ-NP-RT-Y]{2}\d{2}\b/gi, context: /\b(?:medicare|mbi|beneficiary)\b/i },
  { code: 'prescription_number', label: 'Prescription Number (Rx)', description: 'Prescription/Rx numbers in common pharmacy formats', category: 'Healthcare', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', group: 1, re: /\b(?:Rx|prescription)\s*(?:number|no\.?|#)?\s*[:#-]?\s*([A-Z0-9-]{5,12})\b/gi },
  { code: 'hl7_fhir_resource_id', label: 'HL7 FHIR Resource ID', description: 'HL7 FHIR resource references in ResourceType/id format', category: 'Healthcare', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:Patient|Observation|Encounter|Condition|MedicationRequest|Practitioner|Organization)\/[A-Za-z0-9\-.]{1,64}\b/g },
  { code: 'controlled_substances', label: 'Controlled Substance Names', description: 'Names of controlled substances and pharmaceutical ingredients in context', category: 'Healthcare', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:oxycodone|hydrocodone|fentanyl|morphine|amphetamine|methylphenidate|alprazolam)\b/gi },
  { code: 'medical_record_content', label: 'Medical Record Content', description: 'Detects medical record content by identifying clusters of medical terms', category: 'Healthcare', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:diagnosis|symptoms|medication|allergies|patient|blood pressure|lab result|treatment plan)\b[\s\S]{0,200}\b(?:diagnosis|symptoms|medication|allergies|patient|blood pressure|lab result|treatment plan)\b/gi },

  { code: 'court_case_number', label: 'Federal Court Case Number', description: 'US federal court case numbers in standard format (e.g., 1:24-cv-01234)', category: 'Legal', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{1,2}:\d{2}-(?:cv|cr|bk|mc|md)-\d{4,6}\b/gi },
  { code: 'legal_hold_identifier', label: 'Legal Hold Identifier', description: 'Legal hold and litigation hold notices and identifiers', category: 'Legal', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:legal hold|litigation hold)(?:\s*(?:id|notice|identifier))?\s*[:#-]?\s*[A-Z0-9-]{4,20}\b/gi },
  { code: 'confidentiality_notice', label: 'Confidentiality Notice', description: 'Legal confidentiality and non-disclosure notice patterns', category: 'Legal', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:attorney-client privileged|confidentiality notice|subject to non-disclosure|privileged and confidential)\b/gi },
  { code: 'eccn_classification', label: 'Export Control (ECCN)', description: 'Export Control Classification Numbers used in US export regulations', category: 'Legal', sensitivity: 'Medium', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:[0-9][A-E][0-9]{3}|EAR99)\b/g, context: /\b(?:eccn|export control|ear)\b/i },
  { code: 'itar_classification', label: 'ITAR Classification', description: 'International Traffic in Arms Regulations classification markings', category: 'Legal', sensitivity: 'High', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:ITAR controlled|International Traffic in Arms Regulations|USML Category\s+[IVXLC]+)\b/gi },
  { code: 'gdpr_data_subject_id', label: 'GDPR Data Subject Request', description: 'GDPR data subject access request identifiers and markers', category: 'Legal', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:GDPR|data subject access request|DSAR|data subject request)\b(?:.{0,80}\b[A-Z]{2,}-?\d{4,}\b)?/gi },
  { code: 'legal_document_content', label: 'Legal Document Content', description: 'Detects legal document content by identifying clusters of legal terms', category: 'Legal', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:whereas|hereby|indemnify|jurisdiction|plaintiff|defendant|agreement|liability)\b[\s\S]{0,200}\b(?:whereas|hereby|indemnify|jurisdiction|plaintiff|defendant|agreement|liability)\b/gi },

  { code: 'military_dod_id', label: 'Military/DoD ID Number', description: 'Department of Defense ID number (10-digit EDIPI)', category: 'Government', sensitivity: 'High', contextRequired: true, isActive: false, enforceable: false, source: 'builtin', re: /\b\d{10}\b/g, context: /\b(?:dod|edipi|military)\b/i },
  { code: 'fouo_cui_markings', label: 'FOUO/CUI Markings', description: 'For Official Use Only and Controlled Unclassified Information markings', category: 'Government', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:FOUO|FOR OFFICIAL USE ONLY|CUI(?:\/{2}[A-Z0-9\/-]+)?|CONTROLLED UNCLASSIFIED INFORMATION)\b/gi },
  { code: 'nato_classification', label: 'NATO Classification', description: 'NATO security classification markings', category: 'Government', sensitivity: 'High', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\bNATO\s+(?:SECRET|CONFIDENTIAL|RESTRICTED|UNCLASSIFIED)\b/gi },

  { code: 'ip_address_v4', label: 'IPv4 Address', description: 'IPv4 addresses in dotted decimal notation (excludes private ranges)', category: 'Infrastructure', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:\d{1,3}\.){3}\d{1,3}\b/g, validate: v => validIPv4(v) && !isPrivateIPv4(v) },
  { code: 'rfc1918_internal_ip', label: 'Internal/RFC1918 IP Address', description: 'Private network IP addresses (10.x, 172.16-31.x, 192.168.x)', category: 'Infrastructure', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:\d{1,3}\.){3}\d{1,3}\b/g, validate: v => validIPv4(v) && isPrivateIPv4(v) },
  { code: 'aws_arn', label: 'AWS ARN', description: 'AWS resource identifiers in ARN format', category: 'Infrastructure', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\barn:aws[a-z-]*:[a-z0-9-]+:[a-z0-9-]*:\d{12}:[A-Za-z0-9_+=,.@\/-]+\b/g },
  { code: 'gcp_resource_id', label: 'GCP Resource Identifier', description: 'Google Cloud Platform resource paths and project identifiers', category: 'Infrastructure', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\bprojects\/[a-z][a-z0-9-]{4,28}[a-z0-9](?:\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)+\b/g },
  { code: 'azure_resource_id', label: 'Azure Resource ID', description: 'Microsoft Azure resource identifiers', category: 'Infrastructure', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\/subscriptions\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/resourceGroups\/[^\/\s]+\/providers\/[A-Za-z.]+\/[A-Za-z]+\/[^\s"']+/gi },
  { code: 'k8s_secret_ref', label: 'Kubernetes Secret Reference', description: 'References to Kubernetes secrets and configmaps in manifests', category: 'Infrastructure', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /(?:secretKeyRef\s*:\s*[\s\S]{0,120}?name\s*:|kind\s*:\s*Secret\b)/g },
  { code: 'terraform_state_marker', label: 'Terraform State File Content', description: 'Markers indicating Terraform state file content which may contain secrets', category: 'Infrastructure', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /"terraform_version"\s*:\s*"[^"]+"[\s\S]{0,1000}"resources"\s*:/g },

  { code: 'code_detection', label: 'Source Code Block', description: 'Detects code by syntax markers: function defs, imports, class defs', category: 'Code', sensitivity: 'Low', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /```[a-zA-Z0-9_+-]*\n[\s\S]{0,200}?```|(?:^\s*(?:import|export|function|class|const|let|var|def|public|private)\b[^\n]*\n){2,}/gm },
  { code: 'prompt_injection', label: 'Prompt Injection', description: 'Instructions embedded in untrusted content that attempt to hijack the agent', category: 'Prompt Injection', sensitivity: 'High', contextRequired: false, isActive: true, enforceable: false, source: 'builtin', re: /\b(?:ignore (?:all )?(?:previous|prior) instructions|disregard (?:all )?(?:previous|prior) instructions|you are now|reveal (?:the )?system prompt|system prompt|developer message)\b/gi },
  { code: 'ferpa_student_record', label: 'FERPA Student Record', description: 'Markers indicating FERPA-protected student education records', category: 'Education', sensitivity: 'Medium', contextRequired: false, isActive: false, enforceable: false, source: 'builtin', re: /\b(?:student\s*id|transcript|grades?|GPA|course record)\b[\s\S]{0,120}\b(?:student\s*id|transcript|grades?|GPA|course record)\b/gi },
];
